#!/usr/bin/env python3

import spotipy
from time import sleep
from spotipy.oauth2 import SpotifyClientCredentials

scope = 'user-read-currently-playing user-read-playback-state user-modify-playback-state'

sp = spotipy.Spotify(auth_manager=spotipy.SpotifyOAuth(scope=scope))

res = sp.currently_playing()

song = res["item"]
print(song["name"] + " " + str(int((res["progress_ms"] / song["duration_ms"])*100)) + "%")
