-- Generated by nwg-displays on 2025-10-19 at 02:59:05. Do not edit manually.

--monitor=DP-1,2560x1440@179.88Hz,0x0,1.25
--monitor=HDMI-A-1,1920x1080@144hz,2048x0,1.0
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@179.88Hz",
    position = "0x0",
    scale = "1.0",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@144hz",
    position = "2560x0",
    scale = "1.0",
})

